name: SonarQube Cloud
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze:
    name: Analyze with SonarQube
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Use the version your project requires

      # Step 4: Change directory to V3
      - name: Change to V3 directory
        working-directory: ./V3
        run: pwd

      # Step 5: Install dependencies
      - name: Install dependencies
        working-directory: ./V3
        run: npm install

      # Step 6: Run SonarQube Scanner
      - name: Run SonarQube Scanner
        working-directory: ./V3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=Sumit1174_WIL-Bumblebee-MASK \
            -Dsonar.organization=sumit1174 \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
